remote_theme: chrisrhymes/bulma-clean-theme
title: Zero Play
google_analytics: UA-4644630-2
baseurl: /zero-play

defaults:
  - scope:
      path: ""
    values:
      hero_image: /zero-play/images/index_hero.jpg
      hero_darken: true
      twitter:
        card: summary_large_image
      image: /zero-play/images/index_hero.jpg
